services:
  postgres:
    image: postgres:15-alpine
    container_name: rango-critico-db
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
